### PR TITLE
Updated logo, colors to match branding (SOC-9540)

### PR DESCRIPTION
**Pull request by GarySmith**

### CODE REVIEW

**Comment by rsalevsky** [comment]
Can you attach a screenshot of how it looks now?

**Comment by jeremy-moffitt** [comment]
theme_new

**Comment by jeremy-moffitt** [comment]
This was based off of feedback from the brand team, Scott Corfield and Stephanie Bird

**Comment by rsalevsky** [comment]
Can we also change the bar where the logo is in to be a solid color instead of gradient?

**Comment by GarySmith** [comment]
> Can we also change the bar where the logo is in to be a solid color instead of gradient? Maybe how it is done on suse.com? With a green line in between.

The closest example to this suggestion that I could find is the SUSE Manager docs [1], and it also uses 
different fonts and colors and navigation. Most others products' latest releases [2], [3], [4] use the gradient theme (but with old colors).  @asettle Do you have any further direction here?

[1] https://www.suse.com/documentation/suse-manager-4/4.0/suse-manager/installation/install-intro.html
[2] https://www.suse.com/documentation/suse-openstack-cloud-9/book_deployment/data/book_deployment.html
[3] https://www.suse.com/documentation/suse-enterprise-storage-6/book_storage_deployment/data/book_storage_deployment.html
[4] https://www.suse.com/documentation/sle-ha-15/book_sleha_guide/data/book_sleha_guide.html

**Comment by GarySmith** [comment]
I added another commit (which can be easily reverted) to make the change Rick suggested, as shown by the following screenshot. Any preferences?
theme_other

**Comment by rsalevsky** [comment]
@GarySmith Thanks for the change! I like this version much better. :)

**Comment by jeremy-moffitt** [comment]
Yeah I think that looks better... since the new color meant we're not matching the older doc style anyway, might as well go with the cleaner look.

**Pull request merged**
