### PR TITLE
Upgraded FontAwesome 4.7.0 -> 5.7.0

### LINKED ISSUE #7: Upgrade Font Awesome?
I just noticed the included version of Font Awesome is v4.7.0. The current release is v5.7.0

### PR DESCRIPTION
**Pull request by crazyscientist**
* Removed old CSS and font files
* Added new files in `fontawesome` subdir
* This fixes #7

### CODE REVIEW

**Comment by aspiers** [comment]
This needs a rebase.  Also shouldn't it include a compatibility shim, like I did in [Change I06e70e94: Upgrade fontawesome to latest v5.6.3](https://review.openstack.org/#/c/629902/)?

**Comment by crazyscientist** [comment]
Interesting, @jeremy-moffitt has replaced FontAwesome with Material Icons. I guess that makes my pull request sort of obsolete?

**Comment by crazyscientist** [comment]
@jeremy-moffitt, thanks for the heads up. Then I will put some effort in the rebasing.

**Comment by crazyscientist** [comment]
@jeremy-moffitt, @aspiers, would you like to merge this?

**Comment by aspiers** [comment]
@crazyscientist I'm not seeing the "Replaced HTMl classes `fa` with `fas` because `fa` was obsolete in version 5" changes anywhere here - am I going blind or are they not there?

**Comment by crazyscientist** [comment]
@aspiers, thanks for noticing. As the theme has switched to MaterialIcons that part got lost during the rebase.

**Comment by aspiers** [comment]
[**@crazyscientist**](https://github.com/crazyscientist) commented on [February 18, 2019 1:30 PM](https://github.com/SUSE/suse-sphinx-theme/pull/8#issuecomment-464731908 "2019-02-18T13:30:07Z - Replied by Github Reply Comments"):
> @aspiers, thanks for noticing. As the theme has switched to MaterialIcons that part got lost during the rebase.

Got it - so that change is no longer needed?  If so, please can you update the commit message?  Thanks!

**Comment by crazyscientist** [comment]
> Got it - so that change is no longer needed? If so, please can you update the commit message? Thanks!

@aspiers, no problem. The commit message is changed.

**Pull request merged**
