### PR TITLE
Revert "SCRD-6921 - update SUSE theme from UX team feedback"

### PR DESCRIPTION
**Pull request by jeremy-moffitt**
The original changes were based on the eos design system,
which is intended for applications and does not match
what the Documentation team is currently producing.

An updated set of changes will likely be needed to get
a closer match to the docbook xml theme that is used
for most SUSE docs, but if nothing else the pre-change
version of this theme is a much closer match.

This reverts commit 030fa0529d37ebca228094b76021ade6318038b3.

### CODE REVIEW

**Comment by crazyscientist** [comment]
Looks good to me. Maybe you would like to use the `fas` class instead of the `fa` class. Usage of the `fa` class became deprecated with FontAwesome5 ;)

**Comment by jeremy-moffitt** [comment]
pushed an updated that changes the `fa` classes to `fas`

**Comment by dotNomad** [comment]
Nice and clean revert, although I think we should keep the `.gitignore` and `README.md` changes. The additional instructions in the readme are especially handy.

**Comment by jeremy-moffitt** [comment]
doh, I really need to read the comments more carefully before merging, I'll push another PR with the readme and gitignore restored

**Pull request merged**
